GET https://timemanagementsystemserver.onrender.com/api/trainees?page=1&limit=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJQcUVvUmVXMFdyZFpab241TndEaUhqYjFKUGwyIiwiZW1haWwiOiJ4b2xpbnhpd2VuaUBvdXRsb29rLmNvbSIsInJvbGUiOiJzdXBlcl9hZG1pbiIsImlhdCI6MTc1MjIxNjg2MSwiZXhwIjoxNzUyMjQ5MjYxfQ.SY1hbzYMMVSZgDqEpWTOnTnmdgGgXG_TTGk3n-MB-Ko
